---
- name: Update and install
  hosts: all
  become: yes

  tasks:
  - name: Install Docker
    yum:
      name: docker.io
      state: present
  - name: Install Docker Compose
    yum:
      name: docker-compose
      state: present